name: E2E Tests

on:
  pull_request:
    paths: # Only run if relevant files change
      - 'src/**'
      - 'tests/e2e/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'wrangler.jsonc'
      - '.github/workflows/e2e-tests.yml'

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # Grant permissions for wrangler preview deployment URLs
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Deploy Cloudflare Worker Preview
        id: deploy_preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # Deploy the specific 'preview' environment
          command: deploy --env preview

      - name: Setup Playwright
        run: pnpm add -D playwright @playwright/test

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright Tests
        run: pnpm exec playwright test tests/e2e/mcp-inspector.spec.ts
        env:
          # Pass the preview URL from the deployment step to the tests
          # wrangler-action outputs the URL as 'preview_url'
          PREVIEW_URL: ${{ steps.deploy_preview.outputs.preview_url }}
          # You might need other env vars for your tests 